1. Write a Python Program to Add Two Matrices?

In [20]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[10,20,30],[15,25,35],[11,21,31]])

addition = A+B

print("Addition of given matrices:\n",addition )


Addition of given matrices:
 [[11 22 33]
 [19 30 41]
 [18 29 40]]


2. Write a Python Program to Multiply Two Matrices?

In [21]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[5,4,3]])
B = np.array([[4,2,1],[5,8,4],[1,3,2]])

multiplication = A.dot(B)

print("Multiplication of given matrices:\n",multiplication)

Multiplication of given matrices:
 [[17 27 15]
 [47 66 36]
 [43 51 27]]


3. Write a Python Program to Transpose a Matrix?

In [22]:
import numpy as np

A = np.array([[1,2],[4,5],[5,4]])

result = A.transpose()


print("Transpose of given matrix:\n",result)


Transpose of given matrix:
 [[1 4 5]
 [2 5 4]]


4. Write a Python Program to Sort Words in Alphabetic Order?

In [17]:
words=input("Enter sentence : ")

result=sorted(words.split(' '))

print(result)


Enter sentence :  this is trupti


['is', 'this', 'trupti']


5. Write a Python Program to Remove Punctuation From a String?

In [24]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

string = input("Enter a string :")

remove_punc=""

for char in string:
    if char not in punctuations:
         remove_punc = remove_punc+char
            
print(remove_punc)
    

Enter a string : "[this is so ------- wonderful!!@~]"


this is so  wonderful
